In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/drive/MyDrive/students.csv")

Create the DataFrame from the table above. Display: shape,
columns, dtypes, head(5), and tail(3).

In [4]:
df

  StudentID           Name  Age     City Department  Score Grade  Passed
0      S001    Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002   Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003    Karan Patel   20     Pune        CSE     55     C    True
3      S004     Meera Nair   23  Chennai       MECH     42     D    True
4      S005    Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006   Anjali Singh   22   Jaipur        CSE     35     F   False
6      S007    Rohan Verma   20   Mumbai       MECH     67     B    True
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

In [5]:
df.shape

(10, 8)

In [6]:
df.columns

Index(['StudentID', 'Name', 'Age', 'City', 'Department', 'Score', 'Grade',
       'Passed'],
      dtype='object')

In [7]:
df.dtypes

StudentID     object
Name          object
Age            int64
City          object
Department    object
Score          int64
Grade         object
Passed          bool
dtype: object

In [8]:
df.head(5)

  StudentID          Name  Age     City Department  Score Grade  Passed
0      S001   Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True

In [9]:
df.tail(3)

  StudentID           Name  Age     City Department  Score Grade  Passed
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

(2) Run df.info() and df.describe(). From describe(): what is the
mean Score? What is the standard deviation?

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     object
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   City        10 non-null     object
 4   Department  10 non-null     object
 5   Score       10 non-null     int64
 6   Grade       10 non-null     object
 7   Passed      10 non-null     bool
dtypes: bool(1), int64(2), object(5)
memory usage: 702.0+ bytes

In [11]:
df.describe()

             Age      Score
count  10.000000  10.000000
mean   21.500000  67.700000
std     1.080123  20.133168
min    20.000000  35.000000
25%    21.000000  55.750000
50%    21.500000  69.000000
75%    22.000000  85.500000
max    23.000000  92.000000

In [12]:
df["Score"].mean()

np.float64(67.7)

In [13]:
df["Score"].std()

20.13316776973868

(3) Access the 'Name' column using df['Name']. Then access
'Score' and 'Grade' columns together using double brackets

In [14]:
df["Name"]

0      Arjun Mehta
1     Divya Sharma
2      Karan Patel
3       Meera Nair
4      Sahil Gupta
5     Anjali Singh
6      Rohan Verma
7      Pooja Yadav
8      Vivek Kumar
9    Nisha Agarwal
Name: Name, dtype: object

In [15]:
df[["Score","Grade"]]

   Score Grade
0     78     B
1     91     A
2     55     C
3     42     D
4     88     A
5     35     F
6     67     B
7     92     A
8     71     B
9     58     C

 (4) Use df.loc to select: (a) row at index 0, (b) rows 2 to 5, (c)
rows 0–4 but only columns Name, Score, Grade.

In [16]:
df.loc[0]

StudentID            S001
Name          Arjun Mehta
Age                    21
City                Delhi
Department            CSE
Score                  78
Grade                   B
Passed               True
Name: 0, dtype: object

In [17]:
df.loc[2:5]

  StudentID          Name  Age     City Department  Score Grade  Passed
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006  Anjali Singh   22   Jaipur        CSE     35     F   False

In [18]:
df.loc[0:4,["Name","Score","Grade"]]

           Name  Score Grade
0   Arjun Mehta     78     B
1  Divya Sharma     91     A
2   Karan Patel     55     C
3    Meera Nair     42     D
4   Sahil Gupta     88     A

(5) Use df.iloc to select: (a) first 3 rows, (b) last 2 rows, (c) rows
at positions 1, 3, 5 and columns at positions 0, 2, 4.

In [19]:
df.iloc[:3]

  StudentID          Name  Age    City Department  Score Grade  Passed
0      S001   Arjun Mehta   21   Delhi        CSE     78     B    True
1      S002  Divya Sharma   22  Mumbai        ECE     91     A    True
2      S003   Karan Patel   20    Pune        CSE     55     C    True

In [20]:
df.iloc[-2:]

  StudentID           Name  Age   City Department  Score Grade  Passed
8      S009    Vivek Kumar   21   Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22  Delhi       MECH     58     C    True

In [21]:
df.iloc[[1,3,5],[0,2,4]]

  StudentID  Age Department
1      S002   22        ECE
3      S004   23       MECH
5      S006   22        CSE

(6)  Filter students where Score > 80. How many students scored
above 80?

In [22]:
df[df["Score"]>80]

  StudentID          Name  Age     City Department  Score Grade  Passed
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
7      S008   Pooja Yadav   23  Chennai        CSE     92     A    True

In [23]:
len(df[df["Score"]>80])

3

 (7)  Filter students from Delhi who are in CSE department. Show
Name, Score, and Grade only.

In [24]:
df[(df["City"]=="Delhi") & (df["Department"]=="CSE")][["Name","Score","Grade"]]

          Name  Score Grade
0  Arjun Mehta     78     B

 (8)  Find all students who Failed (Passed == False). What is their
average Score?

In [25]:
failed = df[df["Passed"]==False]

failed

  StudentID          Name  Age    City Department  Score Grade  Passed
5      S006  Anjali Singh   22  Jaipur        CSE     35     F   False

In [26]:
failed["Score"].mean()

np.float64(35.0)

 (9)  Filter students whose Name contains the string 'a' (caseinsensitive) using .str.contains().

In [27]:
df[df["Name"].str.contains("a",case=False)]

  StudentID           Name  Age     City Department  Score Grade  Passed
0      S001    Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002   Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003    Karan Patel   20     Pune        CSE     55     C    True
3      S004     Meera Nair   23  Chennai       MECH     42     D    True
4      S005    Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006   Anjali Singh   22   Jaipur        CSE     35     F   False
6      S007    Rohan Verma   20   Mumbai       MECH     67     B    True
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

(10)  Add a new column 'Score_Category': if Score >= 80 →
'Distinction', Score >= 60 → 'Merit', else 'Pass/Fail'. Use
np.where() or nested condition

In [28]:
df["Score_Category"] = np.where(
    df["Score"]>=80,
    "Distinction",
    np.where(
        df["Score"]>=60,
        "Merit",
        "Pass/Fail"
    )
)

df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
3,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
4,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
5,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail
6,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
7,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
8,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
9,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail

(Bonos) Sort the DataFrame by Score in descending order. Reset the
index. Show the top 5 students.

In [29]:
sorted_df = df.sort_values(by="Score",ascending=False)

sorted_df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
7,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
4,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
0,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
8,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
6,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
9,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail
2,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
3,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
5,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail

In [30]:
sorted_df = sorted_df.reset_index(drop=True)

sorted_df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
5,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
6,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail
7,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
8,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
9,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail

In [31]:
sorted_df = sorted_df.reset_index(drop=True)

sorted_df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
5,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
6,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail
7,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
8,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
9,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail

In [32]:
sorted_df.head()

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit

In [33]:
df

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
3,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
4,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
5,S006,Anjali Singh,22,Jaipur,CSE,35,F,False,Pass/Fail
6,S007,Rohan Verma,20,Mumbai,MECH,67,B,True,Merit
7,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
8,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit
9,S010,Nisha Agarwal,22,Delhi,MECH,58,C,True,Pass/Fail

In [34]:
df.to_csv("students_updated.csv",index=False)

print("File Saved Successfully")

File Saved Successfully

In [35]:
from google.colab import files

files.download("students_updated.csv")